object FormularioPadrao: TFormularioPadrao
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'FormularioPadrao'
  ClientHeight = 346
  ClientWidth = 707
  Color = clWindow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
end
